# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'MyFInTech-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Kingfisher'
	pod 'Moya'
	pod 'Moya/RxSwift'
	pod 'Alamofire'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'RIBs'
	pod 'ReactorKit'
	pod 'FlexLayout'
	pod 'PinLayout'

  # Pods for MyFInTech-iOS

end
