# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

use_frameworks!

target 'MyFInTech-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
	pod 'Moya', '~> 15.0'
	pod 'Moya/RxSwift', '~> 15.0'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'FlexLayout'
	pod 'PinLayout'
	pod 'ReactorKit'
	pod 'GoogleSignIn'
	pod 'KakaoSDKUser'

  # Pods for MyFInTech-iOS
end


post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
            end
        end
    end
end
