# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PleaseSaveMyMoney' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Kingfisher'
	pod 'Moya'
	pod 'Moya/RxSwift'
	pod 'Alamofire'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'RIBs'
	pod 'FlexLayout'
	pod 'PinLayout'

  # Pods for PleaseSaveMyMoney

end
